print(ord('A'))
print(chr(65))
print(chr(8364))
print(len("Python 程式設計"))
print(max("Python3"))
print(min("Python3"))
print(str(-123.8))
print("Happy"+"Birthday"+"To"+"Guan")
print(3*"oh")
print('oh'*3)
print("我">"A")
print("1">"A")
print("abc"=="ABC")
print("ABCD">"ABCd")
print('or' in 'forever')
print('over' in "forever")
print('or' not in 'forever')
print('over' not in "forever")

s = "Python 程式設計"
print(s[2:5])
print(s[3:7])
print(s[6:-1])
print(s[:2])
print(s[2:])
